const Discord = require("discord-user-bots");
const client = new Discord.Client("Token goes here.");

client.on.discord_disconnect();
client.on.gateway();
client.on.heartbeat_sent();
client.on.heartbeat_received();
client.on.ready();
client.on.voice_server_update(message);
client.on.user_update(message);
client.on.application_command_create(message);
client.on.application_command_update(message);
client.on.application_command_delete(message);
client.on.interaction_create(message);
client.on.guild_create(message);
client.on.guild_delete(message);
client.on.guild_role_create(message);
client.on.guild_role_update(message);
client.on.guild_role_delete(message);
client.on.thread_create(message);
client.on.thread_update(message);
client.on.thread_delete(message);
client.on.thread_list_sync(message);
client.on.thread_member_update(message);
client.on.thread_members_update(message);
client.on.channel_create(message);
client.on.channel_update(message);
client.on.channel_delete(message);
client.on.channel_pins_update(message);
client.on.guild_member_add(message);
client.on.guild_member_update(message);
client.on.guild_member_remove(message);
client.on.guild_ban_add(message);
client.on.guild_ban_remove(message);
client.on.guild_emojis_update(message);
client.on.guild_stickers_update(message);
client.on.guild_integrations_update(message);
client.on.guild_webhooks_update(message);
client.on.invite_create(message);
client.on.invite_delete(message);
client.on.voice_state_update(message);
client.on.presence_update(message);
client.on.message_create(message);
client.on.message_update(message);
client.on.message_delete(message);
client.on.message_delete_bulk(message);
client.on.message_reaction_add(message);
client.on.message_reaction_remove(message);
client.on.message_reaction_remove_all(message);
client.on.message_reaction_remove_emoji(message);
client.on.typing_start(message);

// Custom made ones
client.on.embed_sent(message);
client.on.message_edit(message);
